name: CI Pipeline  # or whatever name you want

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Email Sender
        uses: wesdevteam/maileraction@v1.2.3
        with:
          to: dchisholm@microsoft.com
          subject: Code update - ship it to Azure
          text: Code update - ship it to Azure
          html: ""   # optional
